version: "3.7"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "gabaithon2309-swagger"
    
    ports:
      - "8002:8080"
    volumes:
      - ./docs/swagger.yaml:/openapi.yaml
    environment:
      SWAGGER_JSON: /openapi.yaml
  python:
    build: docker/python
    container_name: gabaithon2309-python
    ports:
      - "8000:8000"
    volumes:
      - ./:/app